on: [push, pull_request]
name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout code
      uses: actions/checkout@v1
    - name: build
      run: |
        export GO111MODULE=on
        GOOS=darwin  GOARCH=amd64 go build -o bin/game-of-life-darwin-amd64
        GOOS=linux   GOARCH=amd64 go build -o bin/game-of-life-linux-amd64
        GOOS=windows GOARCH=amd64 go build -o bin/game-of-life-windows-amd64.exe
    - name: upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: game-of-life-darwin-amd64
        path: bin/game-of-life-darwin-amd64
    - name: upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: game-of-life-linux-amd64
        path: bin/game-of-life-linux-amd64
    - name: upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: game-of-life-windows-amd64
        path: bin/game-of-life-windows-amd64.exe
